[package]
name = "shapemaker"
version = "1.1.0"
edition = "2021"


[dependencies]
docopt = "1.1.1"
rand = "0.8.5"
serde = "1.0.147"
serde_json = "1.0.91"
svg = "0.13.0"
getrandom = { version = "0.2", features = ["custom"] }